---
services:
  aprendago2:
    image: fabianoflorentino/aprendago2:v0.0.1
    build:
      context: .
      dockerfile: build/Dockerfile.dev
    env_file:
      - configs/.env
    networks:
      - aprendago2
    volumes:
      - .:/aprendago2
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "ps aux |grep 'air' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  aprendago2:
    name: aprendago2
    driver: bridge
